spring.application.name=spring-jpa-example-2
#
sts.datasource.url=jdbc:mysql://localhost:3306/world
sts.datasource.un=root
sts.datasource.pwd=EJZHr4iCKcGYBdXjb89f/w==
sts.datasource.driver=com.mysql.cj.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true



